<?php

namespace DoctrineORM\Proxies\__CG__\BonSortie;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BonSortie extends \BonSortie\BonSortie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array('dateBonSortie' => NULL, 'heureSortie' => NULL, 'numeroCamion' => NULL, 'produit' => NULL);



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->dateBonSortie, $this->heureSortie, $this->numeroCamion, $this->produit);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'numeroBonSortie', 'dateBonSortie', 'heureSortie', 'numeroCamion', 'nomChauffeur', 'origine', 'destination', 'codeUsine', 'login', 'produit', 'totalColis', 'poidsTotal', 'status', 'createdDate', 'updatedDate', 'deletedDate');
        }

        return array('__isInitialized__', 'id', 'numeroBonSortie', 'nomChauffeur', 'origine', 'destination', 'codeUsine', 'login', 'totalColis', 'poidsTotal', 'status', 'createdDate', 'updatedDate', 'deletedDate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BonSortie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->dateBonSortie, $this->heureSortie, $this->numeroCamion, $this->produit);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroBonSortie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroBonSortie', array());

        return parent::getNumeroBonSortie();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateBonSortie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateBonSortie', array());

        return parent::getDateBonSortie();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroContainer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroContainer', array());

        return parent::getNumeroContainer();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroPlomb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroPlomb', array());

        return parent::getNumeroPlomb();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroCamion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroCamion', array());

        return parent::getNumeroCamion();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomChauffeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomChauffeur', array());

        return parent::getNomChauffeur();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrigine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrigine', array());

        return parent::getOrigine();
    }

    /**
     * {@inheritDoc}
     */
    public function getDestination()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestination', array());

        return parent::getDestination();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeUsine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeUsine', array());

        return parent::getCodeUsine();
    }

    /**
     * {@inheritDoc}
     */
    public function getLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogin', array());

        return parent::getLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function getProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduit', array());

        return parent::getProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', array());

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedDate', array());

        return parent::getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedDate', array());

        return parent::getDeletedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroBonSortie($numeroBonSortie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroBonSortie', array($numeroBonSortie));

        return parent::setNumeroBonSortie($numeroBonSortie);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateBonSortie($dateBonSortie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateBonSortie', array($dateBonSortie));

        return parent::setDateBonSortie($dateBonSortie);
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroContainer($numeroContainer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroContainer', array($numeroContainer));

        return parent::setNumeroContainer($numeroContainer);
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroPlomb($numeroPlomb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroPlomb', array($numeroPlomb));

        return parent::setNumeroPlomb($numeroPlomb);
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroCamion($numeroCamion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroCamion', array($numeroCamion));

        return parent::setNumeroCamion($numeroCamion);
    }

    /**
     * {@inheritDoc}
     */
    public function setNomChauffeur($nomChauffeur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomChauffeur', array($nomChauffeur));

        return parent::setNomChauffeur($nomChauffeur);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrigine($origine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrigine', array($origine));

        return parent::setOrigine($origine);
    }

    /**
     * {@inheritDoc}
     */
    public function setDestination($destination)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestination', array($destination));

        return parent::setDestination($destination);
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeUsine($codeUsine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeUsine', array($codeUsine));

        return parent::setCodeUsine($codeUsine);
    }

    /**
     * {@inheritDoc}
     */
    public function setLogin($login)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogin', array($login));

        return parent::setLogin($login);
    }

    /**
     * {@inheritDoc}
     */
    public function setProduit($produit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduit', array($produit));

        return parent::setProduit($produit);
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate($createdDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', array($createdDate));

        return parent::setCreatedDate($createdDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedDate($updatedDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedDate', array($updatedDate));

        return parent::setUpdatedDate($updatedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedDate($deletedDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedDate', array($deletedDate));

        return parent::setDeletedDate($deletedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoidsTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoidsTotal', array());

        return parent::getPoidsTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoidsTotal($poidsTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoidsTotal', array($poidsTotal));

        return parent::setPoidsTotal($poidsTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureSortie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureSortie', array());

        return parent::getHeureSortie();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureSortie($heureSortie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureSortie', array($heureSortie));

        return parent::setHeureSortie($heureSortie);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalColis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalColis', array());

        return parent::getTotalColis();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalColis($totalColis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalColis', array($totalColis));

        return parent::setTotalColis($totalColis);
    }

}
