CREATE TABLE colisage (id INT AUTO_INCREMENT NOT NULL, produitId INT NOT NULL, nombreCarton INT UNSIGNED NOT NULL, quantiteParCarton NUMERIC(10, 2) DEFAULT NULL, codeUsine VARCHAR(60) NOT NULL, createdDate DATETIME DEFAULT NULL, updatedDate DATETIME DEFAULT NULL, deletedDate DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE stock_entree (id INT AUTO_INCREMENT NOT NULL, sortieId INT DEFAULT NULL, produitId INT DEFAULT NULL, quantiteEntree NUMERIC(10, 2) DEFAULT NULL, createdDate DATETIME DEFAULT NULL, updatedDate DATETIME DEFAULT NULL, deleteDate DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE stock_sortie (id INT AUTO_INCREMENT NOT NULL, sortieId INT DEFAULT NULL, produitId INT DEFAULT NULL, quantiteSortie NUMERIC(10, 2) DEFAULT NULL, createdDate DATETIME DEFAULT NULL, updatedDate DATETIME DEFAULT NULL, deleteDate DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE UNIQUE INDEX UNIQ_26A98456F55AE19E ON achat (numero);
CREATE UNIQUE INDEX UNIQ_2843ABC8C1A94FE7 ON bon_sortie (numeroBonSortie);
CREATE UNIQUE INDEX UNIQ_C7440455AEA34913 ON client (reference);
CREATE UNIQUE INDEX UNIQ_72FD14D7F55AE19E ON demoulage (numero);
CREATE UNIQUE INDEX UNIQ_FE866410F55AE19E ON facture (numero);
CREATE UNIQUE INDEX UNIQ_ED55A906F55AE19E ON facture_temp (numero);
ALTER TABLE ligne_colis_bonsortie CHANGE bonSortie_id bonSortie_id INT DEFAULT NULL;
ALTER TABLE ligne_colis_bonsortie ADD CONSTRAINT FK_767FF4661B342D9B FOREIGN KEY (bonSortie_id) REFERENCES bon_sortie (id) ON DELETE CASCADE;
CREATE INDEX IDX_767FF4661B342D9B ON ligne_colis_bonsortie (bonSortie_id);
CREATE UNIQUE INDEX UNIQ_A05D02DBAEA34913 ON mareyeur (reference);
CREATE UNIQUE INDEX UNIQ_E6D6B297A4D60759 ON profil (libelle);

Updating database schema...
