CREATE TABLE stock_achete (id INT AUTO_INCREMENT NOT NULL, achatId INT DEFAULT NULL, produitId INT DEFAULT NULL, quantiteAchetee NUMERIC(10, 2) DEFAULT NULL, createdDate DATETIME DEFAULT NULL, updatedDate DATETIME DEFAULT NULL, deleteDate DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE stock_facture (id INT AUTO_INCREMENT NOT NULL, factureId INT DEFAULT NULL, produitId INT DEFAULT NULL, quantiteFacturee NUMERIC(10, 2) DEFAULT NULL, createdDate DATETIME DEFAULT NULL, updatedDate DATETIME DEFAULT NULL, deleteDate DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE carton DROP FOREIGN KEY FK_41511106325BF03;
ALTER TABLE carton ADD CONSTRAINT FK_41511106325BF03 FOREIGN KEY (demoulage_id) REFERENCES demoulage (id) ON DELETE CASCADE;
ALTER TABLE demoulage ADD numero VARCHAR(60) DEFAULT NULL, ADD quantiteAdemouler NUMERIC(10, 2) DEFAULT NULL, ADD quantiteDemoulee NUMERIC(10, 2) DEFAULT NULL, ADD status INT DEFAULT 0 NOT NULL;

Updating database schema...
Database schema updated successfully! "5" queries were executed
